server: "localhost"
port: "9090"
db: "homeflix"
dbserver: "127.0.0.1"
dbport: "27017"
download: "C:/Users/aryadhira/Documents/Movie"
peerflixpath: "C:/Users/aryadhira/AppData/Roaming/npm/node_modules/peerflix/app.js"
ytsurl: "https://yts.torrentbay.to/api/v2/list_movies.json"
limit: "50"
